### PR TITLE
started debugging, gives error at while RF.stop ~=1

### PR DESCRIPTION
**Pull request by leakp**
I don't get the problem he has here... The cells RF{1:4}.stop exist, so
I don't know why it would say it's not a cell array.

error message: ??? Cell contents reference from a non-cell array object.

Error in ==> feargenET_PFfitting at 43
while RF{1}.stop ~= 1 && RF{2}.stop ~= 1 && RF{3}.stop ~= 1 &&
RF{4}.stop ~= 1

### CODE REVIEW

**Comment by selimonat** [comment]
I cheked the code but cannot understand why it gives this error. Can u check the state of the variables causing crash with "dbstop if error"?

**Comment by selimonat** [comment]
I got it 
RF = PAL_AMRF_updateRF(RF{current_chain}, test, response); %updating RF
must be changed to 
RF{current_chain} = PAL_AMRF_updateRF(RF{current_chain}, test, response); %updating RF
on line 70 hihi

**Comment by leakp** [comment]
Ha! I was there, thought "doesn't it need the current chain index there?" and thought I'll do that after solving the problem up there. It's all in one! Bingo.
Now it runs, I think I'll just need the additional faces in between (so we have a resolution of 45/2, 22.5% degree steps), because now I can't really see if the RF_update works well, because it just can't get finer. But it runs, I was really partying here :)
Thanks!

**Comment by selimonat** [comment]
Ups sorry that was an empty mail
Wait... Before starting with the faces. 
You can output the proposals on the command line so that you can really see the question and answer yourself simulating a participant and you could see if the proposed questions deviate as expected. See what I mean?

**Pull request closed without merging**
